# .github/workflows/deploy-fabric-api.yml

name: Deploy Fabric API on GCP VM and Start Docker Containers

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"] # Ensure this matches the exact name of your build & push workflow
    types:
      - completed

jobs:
  deploy:
    name: Deploy Docker Container to GCP VM
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Step 3: Install and Set Up gcloud SDK
      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Step 4: Deploy to GCP VM via SSH and Execute Deployment Commands
      - name: Deploy to GCP VM
        run: |
          # SSH into the VM and run deployment commands
          gcloud compute --command="
            # Navigate to the deployment directory
            cd /home/fabric-api || exit

            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKER_USERNAME }}/fabric-api:latest

            # Stop and remove existing containers
            docker-compose down

            # Export environment variables
            export OPENAI_API_KEY='${{ secrets.OPENAI_API_KEY }}'
            export DEFAULT_VENDOR='${{ secrets.DEFAULT_VENDOR }}'
            export YOUTUBE_API_KEY='${{ secrets.YOUTUBE_API_KEY }}'
            export DOCKER_USERNAME='${{ secrets.DOCKER_USERNAME }}'

            # Start containers using Docker Compose with the environment variables
            docker-compose up -d
          "
