name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies and build the web app
      - name: Install dependencies
        run: |
          cd web
          npm install

      - name: Build web app
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          DEFAULT_VENDOR: ${{ secrets.DEFAULT_VENDOR }}
        run: |
          cd web
          # echo "window.ENV = {" > dist/config.js
          # echo "\"OPENAI_API_KEY\": \"$OPENAI_API_KEY\"," >> dist/config.js
          # echo "\"YOUTUBE_API_KEY\": \"$YOUTUBE_API_KEY\"," >> dist/config.js
          # echo "\"DEFAULT_VENDOR\": \"$DEFAULT_VENDOR\"" >> dist/config.js
          # echo "};" >> dist/config.js
          npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web/dist
